version: '3.4'

services:
  zoo_app_nginx:
    image: nginx
    container_name: zoo_app_nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./app:/srv/app
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=157.90.22.101
    - NGINX_PORT=80
  zoo_app_phpfpm:
    build: ./app
    container_name: zoo_app_phpfpm
    volumes:
    - ./app:/srv/app
  zoo_app_db:
    image: mysql
    container_name: zoo_app_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD